# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Lucky_Me   # 标题
subtitle: Lucky_Meの博客   # 首页轮播中间的大字
description: XXX学院 | XXX专业 | 网络安全 # 描述
keywords: Luckyzmj 计算机 网络安全   # 关键词
author: Luckyzmj  # 作者名称
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://LuckyZmj.cn
root: /
permalink: posts/:abbrlink.html
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# 指定目录跳过hexo渲染
skip_render:
  - 'tools/*'
  - 'tools/**'
  - 'GoogleHacking/*'
  - 'GoogleHacking/**'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: true    # default false
  custom_css: 

search:
  path: search.xml
  field: post

permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

Plugins:
- hexo-generator-baidu-sitemap
- hexo-generator-sitemap

baidusitemap:
    path: baidusitemap.xml
sitemap:
    path: sitemap.xml
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12  #下半部文章页面显示数
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6   # 推荐文章以及分类标签显示数
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: matery

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo:   https://github.com/tandong123/tandong123.io.MyBlog.git
  branch: master

# baidu submit
baidu_url_submit:
  count: 80                                      # 提交最新的一个链接
  host: www.luckyzmj.cn     # 在百度站长平台中注册的域名
  token: XXXXXXXXXXXXXX    # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt                # 文本文档的地址， 新链接会保存在此文本文档里



live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d-widget-model-shizuku
  # model:
  #   use: live2d-widget-model-wanko
  display:
    position: left
    width: 150
    height: 200
  mobile:
    show: false
  react:
    opacity: 0.7
   
githubEmojis:
  enable: true
  className: github-emoji
  inject: true
  styles:
    # font-size: 5em
    # font-weight: bold
  customEmojis:

# marked:
#   gfm: true
#   pedantic: false
#   breaks: true
#   smartLists: true
#   smartypants: true
#   modifyAnchors: ''
#   autolink: true
#   sanitizeUrl: false
#   headerIds: true

# lazyload configuration  2019.08.14
lazyload:
  enable: true
  onlypost: true
  loadingImg: https://cdn.jsdelivr.net/gh/shw2018/cdn@1.0/sakura/img/loader/orange.progress-bar-stripe-loader.svg    # eg ./images/loading.gif

html_minifier:
  enable: false
  ignore_error: false
  exclude:

css_minifier:
  enable: false
  exclude:
    - '*.min.css'

js_minifier:
  enable: false
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'

image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false


encrypt:
    enable: false
    message:  请输入密码，查看文章